DROP TABLE empleado CASCADE;

--DROP TABLE agente CASCADE;

--DROP TABLE entrenador CASCADE;

DROP TABLE edificio CASCADE;

DROP TABLE piso CASCADE;

DROP TABLE evaluar CASCADE;

DROP TABLE faltar CASCADE;

DROP TABLE curso CASCADE;

DROP TABLE horario_curso CASCADE;

DROP TABLE impartir CASCADE;

DROP TABLE sala CASCADE;

--DROP TABLE sala_operaciones CASCADE;

--DROP TABLE sala_capacitacion CASCADE;

DROP TABLE asistencia CASCADE;

DROP TABLE registro_asistencia CASCADE;

DROP TABLE reservar CASCADE;

DROP TABLE asignar CASCADE;

DROP TABLE estacion CASCADE;

DROP TABLE accesorio CASCADE;

DROP TABLE cliente CASCADE;