ALTER TABLE evaluar DROP CONSTRAINT evaluar_check_faltas;
ALTER TABLE laborar_operaciones DROP CONSTRAINT laborar_operaciones_check_aprobacion;
ALTER TABLE fecha_reservacion_operaciones DROP CONSTRAINT fecha_reservacion_operaciones_check_no_overlap;
ALTER TABLE asignar DROP CONSTRAINT asignar_check_no_overlap;
ALTER TABLE asignar DROP CONSTRAINT asignar_check_no_sunday;
ALTER TABLE horario_curso DROP CONSTRAINT horario_curso_check_weekly_time_limit;