DROP TABLE vivero CASCADE;

DROP TABLE empleado CASCADE;

DROP TABLE cajero CASCADE;

DROP TABLE cuidador CASCADE;

DROP TABLE gerente CASCADE;

DROP TABLE encargado CASCADE;

DROP TABLE cliente CASCADE;

DROP TABLE c_info_planta CASCADE;

DROP TABLE planta CASCADE;

DROP TABLE pago CASCADE;

DROP TABLE efectivo CASCADE;

DROP TABLE tarjeta_credito CASCADE;

DROP TABLE tarjeta_debito CASCADE;

DROP TABLE venta CASCADE;

DROP TABLE venta_en_linea CASCADE;

DROP TABLE venta_fisica CASCADE;

DROP TABLE ayudar CASCADE;

DROP TABLE correo CASCADE;

DROP TABLE telefono_persona CASCADE;

DROP TABLE telefono_vivero CASCADE;