INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (548111,95,'Ameliorated zero administration pricing structure','Chiguang','M',22,'parturient montes','in');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (973458,24,'Re-contextualized discrete ability','Paris 02','F',21,'proin risus','vestibulum ante');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (486533,41,'Devolved human-resource leverage','Hậu Nghĩa','M',68,'nulla','augue');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (786030,99,'Streamlined optimizing help-desk','Rudnichnyy','M',83,'aliquet','at diam');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (20241,39,'Polarised 3rd generation emulation','Karmai','F',34,'pellentesque at','non interdum');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (58827,83,'Fully-configurable mobile groupware','Saint David’s','M',45,'vulputate','mi');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (166591,10,'Organized grid-enabled architecture','Stříbro','M',90,'odio','nec nisi');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (640452,72,'Expanded full-range secured line','El Coco','F',76,'vel','in hac');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (805188,15,'Vision-oriented 3rd generation product','Dongfanghong','M',84,'montes','at velit');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (121838,96,'Object-based mobile concept','Kudang','M',28,'lectus pellentesque','ut');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (45245,69,'User-friendly coherent framework','Lidköping','M',41,'mauris','vitae mattis');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (287054,3,'Advanced leading edge function','Itajaí','M',60,'vel','sit');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (421118,77,'Profound content-based concept','Mucumpiz','M',54,'blandit','integer a');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (229626,18,'Down-sized client-driven ability','Rufino','M',36,'id','eget');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (492312,82,'De-engineered content-based moratorium','Mohelno','F',50,'volutpat','non interdum');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (979925,40,'Down-sized user-facing framework','Loreto','M',79,'mauris','nulla');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (197799,95,'Progressive 24 hour ability','Olutanga','M',83,'accumsan','blandit nam');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (5961,11,'Persevering object-oriented access','Ford','M',55,'mauris','nam tristique');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (272566,57,'Fully-configurable asymmetric superstructure','Zambrów','F',65,'magna','molestie');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (642367,75,'Streamlined eco-centric moderator','Nu’erbage','F',9,'vestibulum eget','libero nullam');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (773635,99,'Networked modular monitoring','Rudo','M',57,'at','morbi sem');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (261004,61,'Grass-roots even-keeled moderator','Kohila','F',72,'aliquet pulvinar','consequat');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (227634,84,'Versatile 3rd generation core','Sarulla','M',97,'amet','fermentum');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (595289,35,'Expanded object-oriented moderator','Xianlong','F',3,'iaculis diam','non mauris');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (8068,53,'Horizontal heuristic encoding','Santa Rita Aplaya','F',19,'lacinia','nisi');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (665015,3,'Enhanced optimal array','Zhongxin','F',58,'mus etiam','at');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (44030,57,'Pre-emptive homogeneous neural-net','Le Mans','F',48,'quam nec','vestibulum');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (972187,58,'Monitored value-added info-mediaries','Gungguh','M',48,'orci','lorem id');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (932951,42,'Function-based needs-based budgetary management','Rezovac','M',50,'aenean','mattis odio');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (412473,11,'Reverse-engineered bi-directional moratorium','Lyakhovtsy','F',43,'id','quam');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (411589,18,'Proactive fresh-thinking process improvement','Casa Quemada','F',45,'aliquam quis','et ultrices');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (278971,60,'Cross-group systematic open system','San Sebastian','M',2,'congue','at lorem');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (704365,90,'Enhanced 6th generation time-frame','Cueto','F',58,'amet','sapien placerat');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (558590,92,'Innovative full-range alliance','Dafengdui','M',41,'pretium','tortor id');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (768621,99,'Proactive didactic matrix','Nunleu','F',17,'ac enim','at');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (511083,2,'Switchable fresh-thinking success','Chuzhou','F',41,'adipiscing lorem','quis odio');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (334885,86,'Open-architected disintermediate interface','Ludvika','M',53,'ut erat','vestibulum');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (261478,18,'Secured disintermediate methodology','Petrolia','F',19,'dis','quam');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (344081,32,'Distributed static methodology','Carolina','F',38,'consequat','in imperdiet');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (390058,20,'Polarised bifurcated productivity','Březová nad Svitavou','M',54,'sodales','blandit non');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (427852,27,'Centralized explicit encoding','Veiga','M',92,'justo','curabitur in');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (577894,24,'Customer-focused 5th generation monitoring','Languan','M',69,'duis faucibus','metus vitae');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (631042,47,'Programmable intermediate hierarchy','Kingscourt','M',61,'congue','libero convallis');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (691596,50,'Integrated encompassing firmware','Eira Nova','M',57,'orci','dolor');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (646424,29,'Open-architected contextually-based definition','Bastia','M',11,'hac','elementum');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (221123,9,'Enterprise-wide radical workforce','Norfolk','F',73,'sit amet','venenatis turpis');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (15330,82,'Robust holistic orchestration','Jeponkrajan','M',80,'nulla eget','tristique');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (179168,55,'Object-based regional infrastructure','Baiquan','M',31,'semper interdum','in');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (671196,88,'Mandatory non-volatile interface','Deventer','F',24,'natoque','quis');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (357298,95,'Integrated systematic algorithm','Qaxa','F',92,'ultricies eu','nulla ultrices');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (702745,5,'Optimized 6th generation project','Bayt ‘Ūr at Taḩtā','M',24,'morbi a','commodo vulputate');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (842443,47,'Vision-oriented transitional strategy','Bulgan','M',30,'mauris vulputate','risus semper');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (910612,7,'Compatible hybrid secured line','Leiria','M',10,'rhoncus aliquam','lacinia');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (982061,69,'Assimilated bi-directional focus group','Punkalaidun','M',7,'imperdiet','cras mi');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (333212,88,'Implemented encompassing budgetary management','Strasbourg','F',86,'in','in');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (40940,1,'Business-focused web-enabled flexibility','Fengshan','M',53,'nullam','arcu');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (259324,5,'Advanced multi-state moratorium','Karak City','M',60,'eu nibh','nibh in');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (988906,89,'Integrated 3rd generation pricing structure','Lanuza','F',71,'blandit lacinia','natoque');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (319008,87,'Up-sized regional database','Vinha','M',25,'vivamus metus','sem');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (576354,56,'Phased upward-trending flexibility','Luksuhin','F',1,'tellus','duis');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (375299,21,'Profound needs-based neural-net','Dorp Antriol','F',86,'sed lacus','maecenas tristique');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (34098,34,'Front-line radical website','Karobokan','M',83,'at','in');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (751185,20,'Balanced methodical task-force','Korczyna','M',37,'risus semper','congue');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (942271,85,'Focused real-time firmware','Sete Lagoas','M',19,'eu pede','lacinia aenean');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (192228,17,'Self-enabling fresh-thinking access','Ostrožac','F',82,'viverra diam','nulla');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (942112,49,'Reduced actuating knowledge user','Enyerhyetykaw','F',45,'dictumst','ante ipsum');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (35321,99,'Optional methodical approach','Marteleira','F',41,'turpis','at');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (519109,89,'Fundamental bottom-line benchmark','Sabanalarga','F',39,'erat','quisque');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (944813,70,'Organic asynchronous parallelism','Annonay','M',61,'ut nunc','dapibus');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (616441,4,'Open-architected systemic encryption','Campaka','F',11,'venenatis','nulla');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (673593,3,'Monitored local groupware','Junín','M',18,'eu','potenti in');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (997173,49,'Focused asymmetric budgetary management','Bukor','M',13,'aliquam','maecenas rhoncus');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (819809,80,'Reverse-engineered national task-force','Lazi','F',59,'id ornare','pellentesque viverra');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (327621,26,'Optimized empowering solution','Xiji','M',52,'sed','parturient');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (328417,23,'Stand-alone value-added superstructure','Maputi','F',77,'orci','luctus');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (455718,20,'Balanced bandwidth-monitored ability','Belsk Duży','F',55,'amet diam','rutrum ac');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (313638,59,'Fully-configurable 6th generation array','Costeira do Pirajubae','F',83,'condimentum curabitur','lectus in');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (714636,74,'Synergized homogeneous process improvement','Sendang','F',91,'duis faucibus','vulputate');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (987560,65,'Centralized non-volatile info-mediaries','Bílina Kyselka','F',11,'donec','non');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (329497,62,'Exclusive bifurcated customer loyalty','Constanza','F',84,'massa','nulla');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (551410,50,'Multi-lateral well-modulated challenge','Warungpeuteuy','F',27,'nisl','consequat');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (744739,89,'Compatible client-server capability','Rafael Hernandez Ochoa','F',52,'pellentesque volutpat','quam');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (737356,79,'Function-based mission-critical info-mediaries','Ábrego','M',44,'natoque','id luctus');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (736881,60,'Profit-focused zero administration alliance','Costa Rica','M',94,'quisque','nulla ut');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (120241,17,'Exclusive mobile success','Denov','F',73,'eget rutrum','consectetuer adipiscing');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (26842,74,'Sharable tangible circuit','Fentange','F',23,'lacinia','orci mauris');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (401189,78,'Mandatory real-time extranet','Kengkou','F',71,'purus','tempus vel');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (425529,57,'Optional coherent system engine','Hong’an','M',35,'suspendisse','parturient montes');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (91296,47,'Inverse local hierarchy','Arcueil','M',88,'egestas','lacinia');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (467885,33,'Multi-tiered dynamic database','Wadeng','M',90,'tristique','felis eu');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (542180,11,'Seamless zero defect synergy','Xianghuaqiao','M',18,'accumsan tortor','ligula');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (3005,100,'Managed stable contingency','Świętajno','M',8,'proin interdum','erat');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (273780,5,'Multi-channelled needs-based moratorium','Nové Sedlo','M',21,'lacinia','lacus purus');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (125589,27,'Multi-tiered fresh-thinking complexity','Housuo','M',61,'volutpat dui','justo lacinia');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (192786,47,'Seamless high-level toolset','Bajia','M',40,'luctus','nulla quisque');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (615615,53,'Phased needs-based access','Añatuya','F',71,'vivamus vel','quam turpis');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (385094,62,'Open-source mission-critical circuit','Kebonkaret','M',85,'faucibus accumsan','in hac');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (689605,36,'Balanced systemic focus group','Cineumbeuy','F',87,'vivamus','adipiscing');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (565288,23,'Cross-group disintermediate archive','Bela Vista','F',7,'ante vel','aenean auctor');
INSERT INTO c_info_planta(nombre,riego,cuidados,area,genero,precio,tipo_luz,tipo_sustrato) VALUES (432542,34,'Ergonomic 5th generation support','Blarney','M',45,'tincidunt','bibendum');